[tool.poetry]
name = "commaagentsdemo"
version = "0.1.0"
description = "A demo for showing the best of comma agents to investors"
authors = ["Nathaniel Hatch-Martinez <nate@nateageek.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
<<<<<<< Updated upstream
comma-agents = "^0.0.7"
=======
comma-agents = "^0.0.8"
>>>>>>> Stashed changes
faker = "^27.0.0"
seedir = "^0.5.0"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
